google_analytics: false
uppercase_capsule: true
theme_config_check: true
show_update_time: false
player:
  disable_on_mobile: false
  position: before_sidebar
  aplayer:
    enable: false
    options:
      autoplay: null
      loop: null
      preload: null
      order: null
      fixed: null
      audio: []
      lrcType: null
      volume: null
      listFolded: null
      mutex: null
  meting:
    enable: false
    meting_api: null
    options:
      id: 2265921590
      server: netease
      type: playlist
      auto: null
disqus:
  enable: false
  shortname: null
  count: true
utterances:
  enable: false
  repo: owner/repo
  issue_term: title
  theme: auto
baidu_analytics: false
local_font:
  article:
    - -apple-system
    - PingFang SC
    - Microsoft YaHei
    - sans-serif
  code:
    - Menlo
    - Monaco
    - Consolas
    - monospace
anchor_icon: null
animation:
  enable: true
  options:
    header:
      title: slide-up
      subTitle: slide-down
    home:
      post: fade-up
      widget: fade-up
      sidebar: fade-up
    article:
      whole: fade-up
      date: zoom-in
      category: zoom-in
      tag: zoom-in
      comment: zoom-in
      reading: zoom-in
      nav: fade-up
    archive:
      whole: fade-up
      tag: zoom-in
      category: zoom-in
      section: fade-up
      nav: fade-up
twikoo:
  enable: false
  envId: null
  region: null
summary:
  enable: false
  style: subtitle
internal_theme:
  light:
    --color-red-3-shadow: rgba(255, 78, 78, 0.3)
    --red-5-5: "#fff3f3"
    --highlight-comment: "#7d7d7d"
    --highlight-background: "#fdfdfd"
    --highlight-deletion: "#b31d28"
    --highlight-orange: "#e36209"
    --highlight-nav: "#f5f5f5"
    --highlight-green: "#22863a"
    --highlight-deletion-bg: "#ffeef0"
    --highlight-yellow: "#cb911d"
    --highlight-scrollbar: "#d6d6d6"
    --highlight-selection: "#e9e9e988"
    --highlight-blue: "#032f62"
    --red-0: "#ff0000"
    --red-1: "#ff5252"
    --highlight-purple: "#6f42c1"
    --highlight-addition: "#22863a"
    --highlight-aqua: "#005cc5"
    --red-2: "#ff7c7c"
    --red-3: "#ffafaf"
    --red-4: "#ffd0d0"
    --highlight-red: "#d73a49"
    --red-5: "#ffecec"
    --red-6: "#fff7f7"
    --highlight-foreground: "#24292e"
    --color-red-6-shadow: rgba(255, 78, 78, 0.6)
    --highlight-addition-bg: "#f0fff4"
  dark:
    --red-5-5: rgba(255,236,236,0.05)
    --highlight-comment: "#8b949e"
    --highlight-background: "#1e2027"
    --highlight-deletion: "#ffa198"
    --highlight-orange: "#ffa657"
    --highlight-nav: "#222830"
    --highlight-green: "#7ee787"
    --highlight-deletion-bg: "#490202"
    --highlight-yellow: "#ffcc66"
    --highlight-scrollbar: "#454d59"
    --highlight-selection: "#51515155"
    --highlight-blue: "#79c0ff"
    --highlight-purple: "#d2a8ff"
    --highlight-addition: "#7ee787"
    --highlight-aqua: "#a5d6ff"
    --red-4: rgba(255, 208, 208, 0.5)
    --highlight-red: "#ff7b72"
    --red-5: rgba(255,228,228,0.15)
    --red-6: rgba(255, 243, 243, 0.2)
    --highlight-foreground: "#c9d1d9"
    --highlight-addition-bg: "#04260f"
custom_avatar: /images/uploads/site/微信图片_20260411225246_53_2.jpg
firework:
  enable: true
  disable_on_mobile: false
  options:
    excludeElements:
      - a
      - button
    particles:
      - shape: circle
        move:
          - emit
        easing: easeOutExpo
        colors:
          - var(--red-1)
          - var(--red-2)
          - var(--red-3)
          - var(--red-4)
        number: 20
        duration:
          - 1200
          - 1800
        shapeOptions:
          radius:
            - 16
            - 32
          alpha:
            - 0.3
            - 0.5
      - shape: circle
        move:
          - diffuse
        easing: easeOutExpo
        colors:
          - var(--red-0)
        number: 1
        duration:
          - 1200
          - 1800
        shapeOptions:
          radius: 20
          alpha:
            - 0.2
            - 0.5
          lineWidth: 6
toc_options:
  list_number: true
  min_depth: 1
  max_depth: 6
quicklink:
  enable: false
  timeout: 3000
  priority: true
  ignores: []
copyright: null
service_worker:
  enable: false
vendor:
  cdn_jsdelivr_gh: https://cdn.jsdelivr.net/gh/
  cdn_jsdelivr_npm: https://cdn.jsdelivr.net/npm/
  fastly_jsdelivr_gh: https://fastly.jsdelivr.net/gh/
  fastly_jsdelivr_npm: https://fastly.jsdelivr.net/npm/
  unpkg: https://unpkg.com/
  webcache: https://npm.webcache.cn/
  js:
    aplayer:
      src: webcache|aplayer@1.10.1/dist/APlayer.min.js
      integrity: sha384-gdGYZwHnfJM54evoZhpO0s6ZF5BQiybkiyW7VXr+h5UfruuRL/aORyw+5+HZoU6e
    twikoo:
      src: webcache|twikoo@1.6.44/dist/twikoo.all.min.js
      integrity: sha384-kwWLC0HjeZZnVPqCJ1AncI8tsk+kQqF9TbAmCclcc9Z0hGkfgHRzeQZxmdmZhE0K
    meting:
      src: webcache|meting@2.0.1/dist/Meting.min.js
      integrity: sha384-ASVlpKF80A22OXTK3tfEjZm1EL6uFMKIC4p8+0maanw1S/IyB+Y4JG+ZDU7GpKE8
    firework:
      src: webcache|mouse-firework@0.2.0/dist/index.umd.js
      integrity: sha384-qi9WggRt19tv8Vc7pCHW3ulMNLwrn515zaLEWZjl1px07vz8+pUoWX8n1rgq282T
    quicklink:
      src: webcache|quicklink@3.0.1/dist/quicklink.umd.js
      integrity: sha384-caMDqvgav/HWdEYQU1QRRHMLleigpL1YHAG0m371DhzfL8rRzUyOb+bEHtwlmYjD
    photoswipe:
      src: webcache|photoswipe@5.4.4/dist/photoswipe.esm.min.js
      integrity: sha384-WkkO3GCmgkC3VQWpaV8DqhKJqpzpF9JoByxDmnV8+oTJ7m3DfYEWX1fu1scuS4+s
    mermaid:
      src: webcache|mermaid@11.12.0/dist/mermaid.min.js
      integrity: sha384-o+g/BxPwhi0C3RK7oQBxQuNimeafQ3GE/ST4iT2BxVI4Wzt60SH4pq9iXVYujjaS
    instantsearch:
      src: webcache|@reimujs/instantsearch.js@4.57.0-beta.1/dist/instantsearch.production.min.js
      integrity: sha384-aagKMe8nkqaP2DYQc8kkYOL5l+M5Q2WH/Uhr4teOh0Ybp0RZj0kUSDm45qPikMjK
    typed:
      src: webcache|typed.js@2.1.0/dist/typed.umd.js
      integrity: sha384-cMrTlShXEGSdSFA359p+3aVUxK/R+0TAfbRZMcTlAn8yqzxEDj05QsS65nTFMMj4
    pangu:
      src: webcache|pangu@4.0.7/dist/browser/pangu.min.js
      integrity: sha384-HeUHqi0nVsPUm/E0ss7OfnIV/yD96JWB8ehZvUuoVax9DpNHL17jj9pdfXHzqDxm
    photoswipe_lightbox:
      src: webcache|photoswipe@5.4.4/dist/photoswipe-lightbox.esm.min.js
      integrity: sha384-DiL6M/gG+wmTxmCRZyD1zee6lIhawn5TGvED0FOh7fXcN9B0aZ9dexSF/N6lrZi/
    gitalk:
      src: webcache|gitalk@1.8.0/dist/gitalk.min.js
      integrity: sha384-kspnZUWBoSWwoJHa0hBCXYbHGbhvU/lcEH5O8eVbSDhbPwsiVUTp/aGX/z/5EuMA
    qrcode:
      src: webcache|qrcode@1.5.1/build/qrcode.js
      integrity: sha384-VT1EeewTCEXgndcPMQ0PzV+uVFYjxFIjmAA7s5gcMX9t4Dt5TD+OVQIn7NJWIXn7
    live2d_widgets:
      src: webcache|live2d-widgets@0.9.0/autoload.js
      integrity: sha384-poTN7wN/SqNhQqo3jdFeX20ikddWeFGkUkDEzsKjgH/ez8aQLn81oI0Cw6q5xNyB
    svg_pan_zoom:
      src: webcache|svg-pan-zoom@3.6.2/dist/svg-pan-zoom.min.js
      integrity: sha384-GGX4llYprEPGp9w5caepn95YWAEflHnsA5ewt+Y+cBEb95og5cXKllnWKSELlzbx
    dompurify:
      src: webcache|dompurify@3.2.6/dist/purify.min.js
      integrity: sha384-JEyTNhjM6R1ElGoJns4U2Ln4ofPcqzSsynQkmEc/KGy6336qAZl70tDLufbkla+3
    material_theme:
      src: webcache|material-theme@1.0.0/dist/material-theme.umd.js
      integrity: sha384-vLev0II0HKFaxkcm+/7kX5IGwVFBASkGchU311wmU/veIj2bB0UcBkQbW6yw2asK
    katex:
      src: webcache|katex@0.16.24/dist/katex.min.js
      integrity: sha384-MWNUH0WmtsYGhn2cbH6ELRCbf9LG3QDqCC+gqPB3IBNO35xjZK3Ejb6oONRpDbPg
    algolia:
      src: webcache|algoliasearch@4.17.1/dist/algoliasearch-lite.umd.js
      integrity: sha384-xvLS0jfKuoREs7pqkRI/OI8GcqohO5S+jQz7ZBtQXnsXmD+9jDOOY4cL6dCPzlrk
    busuanzi:
      src: webcache|busuanzi@2.3.0/bsz.pure.mini.js
      integrity: sha384-0M75wtSkhjIInv4coYlaJU83+OypaRCIq2SukQVQX04eGTCBXJDuWAbJet56id+S
    pjax:
      src: webcache|theme-shokax-pjax@0.0.3/dist/index.umd.js
      integrity: sha384-xneY1WY8hOfUzswrE4CrYq35N4BdVcxqxwHPr9zawE/jMSCxD+jAPU55x/jj3wlf
    pace:
      src: webcache|pace-js@1.2.4/pace.min.js
      integrity: sha384-k6YtvFUEIuEFBdrLKJ3YAUbBki333tj1CSUisai5Cswsg9wcLNaPzsTHDswp4Az8
    clipboard:
      src: webcache|clipboard@2.0.11/dist/clipboard.min.js
      integrity: sha384-J08i8An/QeARD9ExYpvphB8BsyOj3Gh2TSh1aLINKO3L0cMSH2dN3E22zFoXEi0Q
    snapdom:
      src: webcache|@zumer/snapdom@1.9.14/dist/snapdom.min.js
      integrity: sha384-OEQ+fJp/Mvi2uzBREXybtxryJvLytWapuHu4EE6LPwTKUwATYcc55tPPcZTzVcmx
    katex_auto_render:
      src: webcache|katex@0.16.24/dist/contrib/auto-render.min.js
      integrity: sha384-hCXGrW6PitJEwbkoStFjeJxv+fSOOQKOPbJxSfM6G5sWZjAyWhXiTIIAmQqnlLlh
    mathjax:
      src: webcache|mathjax@3.2.2/es5/tex-mml-chtml.js
      integrity: sha384-Wuix6BuhrWbjDBs24bXrjf4ZQ5aFeFWBuKkFekO2t8xFU0iNaLQfp2K6/1Nxveei
    live2d:
      base: fastly_jsdelivr_gh|D-Sketon/plugin-live2d/
      js: fastly_jsdelivr_gh|D-Sketon/plugin-live2d/js/live2d-autoload.js
    md5:
      src: webcache|blueimp-md5@2.19.0/js/md5.min.js
      integrity: sha384-JmVtRz6RWiXnA14QbIOJzPuU3MidULOpBP66deeLLyyoF4Tr/gZlbkHkL6vTthxH
    lazysizes:
      src: webcache|lazysizes@5.3.2/lazysizes.min.js
      integrity: sha384-3gT/vsepWkfz/ff7PpWNUeMzeWoH3cDhm/A8jM7ouoAK0/fP/9bcHHR5kHq2nf+e
    waline:
      src: webcache|@waline/client@2.15.8/dist/waline.mjs
      integrity: sha384-9sbqJjrfGjbkI6/PI4nU/MvBfEmkkPC4YK9I4zBeMIf1CVCZdCMH/KinBEAZII/5
    valine:
      src: webcache|valine@1.5.1/dist/Valine.min.js
      integrity: sha384-3ma91AExDeMAZ1rjTjaP8V2A2obQE+s5ltKRwYlwdpArz9xVbp0tF3b0VV2ACNPn
  css:
    photoswipe:
      src: webcache|photoswipe@5.4.4/dist/photoswipe.css
      integrity: sha384-IfxC36XL/toUyJ939C73PcgMuRzAZuIzZxE38drsmO5p6jD7ei+Zx/1oA/0l8ysE
    katex:
      src: webcache|katex@0.16.24/dist/katex.min.css
      integrity: sha384-tTgKLjMYmJr94v8qu2PE5MUGSMbyN2xiH266JUB3gpm8vnnJywd1dWSOEfrFz+YI
    waline:
      src: webcache|@waline/client@2.15.8/dist/waline.css
      integrity: sha384-vltfZtesCdl6NYVcFVcjEaIi5RpNvZe9t7fXvq8twVtcoy+Ub9QgnxUYJmwOhYCK
    gitalk:
      src: webcache|gitalk@1.8.0/dist/gitalk.css
      integrity: sha384-X7z7PUv2B67D8sPJyzDyGZSco1ADwmdI7ed4eCGtTKkClfyDFpPL9WgAn9XVr/Io
    fontawesome:
      high_priority:
        - src: webcache|@fortawesome/fontawesome-free@7.1.0/css/regular.min.css
          integrity: sha384-4qYppzjH8EiA+cGdaubu2vL7Rk8WGiqCSj7oRuP1uwtFWkfKNHD20lPfcrbQc8dU
        - src: webcache|@fortawesome/fontawesome-free@7.1.0/css/solid.min.css
          integrity: sha384-wbMWab3UDSPm2kvIgVOn/d9KPTecgPU1+Nb3zoQrm/oVu0EkPL6IaKinjbwW0rum
      low_priority:
        - src: webcache|@fortawesome/fontawesome-free@7.1.0/css/brands.min.css
          integrity: sha384-KTGeC2hIMzpeQakhsmzB9bZfhCD5xZZCgI1iZH6f/O457SxzlkzTQg/WXFNoi3ih
        - src: webcache|@fortawesome/fontawesome-free@7.1.0/css/v5-font-face.min.css
          integrity: sha384-nJ1ThfldViXoLpJ6jlKcP2beas8BMbYq26SG9Hi8cH89bZi4RZ644v7helMCqJxd
        - src: webcache|@fortawesome/fontawesome-free@7.1.0/css/v4-font-face.min.css
          integrity: sha384-UlkrhOIvZxJFd4MElSUp7ow6/RUeYKi/orfCZIRRiOENFuQPIAA3T3HjYfmBRhNq
    aos:
      src: webcache|@reimujs/aos@0.1.2/dist/aos.css
      integrity: sha384-GMRP93c6Hkz9JVKGAuRR3nTS7M07RwPgTFenXiosjq2VbVgvdDNcz1g6Mkj8AONa
    aplayer:
      src: webcache|aplayer@1.10.1/dist/APlayer.min.css
      integrity: sha384-tLMkTWh2pfXNWGFlUS0w1TFtRG5xZ9lPWFOooj+vDDLIL+xBGQU/voDBY5XE2lVh
toc: true
recent_posts_limits: 5
math:
  enable: false
  katex:
    enable: true
    autoRender: false
  mathjax:
    enable: false
    options:
      tex:
        tags: ams
        useLabelIds: true
        inlineMath:
          - - $
            - $
          - - \\(
            - \\)
        displayMath:
          - - $$
            - $$
          - - \\[
            - \\]
        processEscapes: true
        processEnvironments: true
        autoload:
          color: []
          colorv2:
            - color
        packages:
          "[+]":
            - noerrors
      options:
        skipHtmlTags:
          - script
          - noscript
          - style
          - textarea
          - pre
          - code
        ignoreHtmlClass: tex2jax_ignore
        processHtmlClass: tex2jax_process
      loader:
        load:
          - input/asciimath
          - "[tex]/noerrors"
mermaid:
  enable: false
  zoom: false
layout:
  max_width: 1350px
pangu:
  enable: false
theme_version_check: true
dark_mode:
  enable: auto
triangle_badge:
  enable: false
  icon: github
  link: https://github.com/D-Sketon/hexo-theme-reimu
banner: /images/uploads/site/ef701efb0445ed195669f237ddc63619.jpg
show_count: false
social:
  github: https://github.com/TIAN3379
gitalk:
  enable: false
  clientID: null
  clientSecret: null
  repo: null
  owner: null
  admin: null
  md5: false
live2d_widgets:
  enable: false
  position: left
font:
  enable: true
  article:
    - Mulish
    - Noto Serif SC
  code: null
widgets: null
giscus:
  emitMetadata: 0
  enable: false
  theme:
    ? light
    ? dark
  strict: 0
  repoId: null
  mapping: mapping
  repo: null
  inputPosition: bottom
  reactionsEnabled: 1
  categoryId: null
  category: null
banner_srcset:
  enable: false
  srcset:
    - src: /images/banner-600w.webp
      media: "(max-width: 479px)"
    - src: /images/banner-800w.webp
      media: "(max-width: 799px)"
    - src: /images/banner.webp
      media: "(min-width: 800px)"
material_theme:
  enable: false
pjax:
  enable: false
rss: atom.xml
pace:
  enable: true
clarity: false
generator_search:
  enable: true
  field: post
  content: true
favicon: /images/favicon.ico
injector:
  head_begin: null
  head_end:
    - <link rel="stylesheet" href="/css/home-admin-entry.css">
  body_begin: null
  body_end:
    - <script defer src="/js/home-admin-entry.js"></script>
  sidebar_begin: null
  sidebar_end: null
icon_font: 4552607_a0oqhord1y
top:
  enable: true
  position: right
  icon:
    url: ../images/taichi.png
    rotate: true
    mask: true
preloader:
  enable: true
  text:
    zh-CN: 少女祈祷中...
    zh-TW: 少女祈禱中...
    en: Loading...
    ja: 少女祈祷中...
    pt-BR: Carregando...
  icon: null
  rotate: true
clipboard:
  success:
    en: Copy successfully (*^▽^*)
    zh-CN: 复制成功 (*^▽^*)
    zh-TW: 複製成功 (*^▽^*)
    ja: コピー成功 (*^▽^*)
    pt-BR: Copiado com sucesso (*^▽^*)
  fail:
    en: Copy failed (ﾟ⊿ﾟ)ﾂ
    zh-CN: 复制失败 (ﾟ⊿ﾟ)ﾂ
    zh-TW: 複製失敗 (ﾟ⊿ﾟ)ﾂ
    ja: コピー失敗 (ﾟ⊿ﾟ)ﾂ
    pt-BR: Falha ao copiar (ﾟ⊿ﾟ)ﾂ
  copyright:
    enable: false
    count: 50
    license_type: by-nc-sa
algolia_search:
  enable: false
  hits:
    per_page: 10
icp:
  ? icpnumber
  ? beian
  ? recordcode
archive_type: monthly
reimu_cursor:
  enable: true
  cursor:
    default: ../images/cursor/reimu-cursor-default.png
    pointer: ../images/cursor/reimu-cursor-pointer.png
    text: ../images/cursor/reimu-cursor-text.png
cover: null
subtitle:
  typing:
    backSpeed: 50
    startDelay: 300
    strings: null
    enable: false
    loop: true
    cursorChar: "|"
    typeSpeed: 100
    showCursor: true
    smartBackspace: false
    shuffle: true
    backDelay: 2000
excerpt_link: Read More
avatar: avatar.webp
open_graph:
  enable: true
  options:
    default_og_image: /images/banner.webp
only_show_capsule_in_index: false
sponsor:
  enable: false
  tip:
    zh-CN: 请作者喝杯咖啡吧
    zh-TW: 請作者喝杯咖啡吧
    en: Buy me a coffee
    ja: コーヒーを買ってください
    pt-BR: Compre-me um café
  icon:
    url: ../images/taichi.png
    rotate: true
    mask: true
  qr: null
moe_icp:
  ? icpnumber
footer:
  since: 2020
  powered: true
  count: true
  busuanzi: true
  icon:
    url: ../images/taichi.png
    rotate: true
    mask: true
code_block:
  expand: true
home_categories:
  enable: false
  content:
    - ? categories
      ? cover
    - ? categories
      ? cover
tagcloud_limits: null
sidebar:
  position: right
  menu: true
  article:
    show_common: true
outdate:
  enable: false
  daysAgo: 180
  message:
    en: This article was last updated on {time}. Please note that the content may no
      longer be applicable.
    zh-CN: 本文最后更新于 {time}，请注意文中内容可能已不适用。
    zh-TW: 本文最後更新於 {time}，請注意文中內容可能已不適用。
    ja: この記事は最終更新日：{time}。記載内容が現在有効でない可能性がありますのでご注意ください。
    pt-BR: Este artigo foi atualizado pela última vez em {time}. Observe que o
      conteúdo pode não ser mais aplicável.
tag_limits: null
custom_font:
  enable: false
  article: null
  code: null
live2d:
  enable: false
  position: left
waline:
  enable: false
  requiredMeta:
    - nick
    - mail
  meta:
    - nick
    - mail
    - link
  emoji:
    - https://unpkg.com/@waline/emojis@1.2.0/weibo
    - https://unpkg.com/@waline/emojis@1.2.0/alus
    - https://unpkg.com/@waline/emojis@1.2.0/bilibili
    - https://unpkg.com/@waline/emojis@1.2.0/qq
    - https://unpkg.com/@waline/emojis@1.2.0/tieba
    - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
  serverURL: null
  pageSize: 10
  wordLimit: 0
  pageview: true
  locale: {}
i18n:
  enable: false
  type:
    - page
    - post
  generator:
    - archive
    - category
    - tag
    - index
  languages:
    - zh-CN
    - en
article_copyright:
  enable: false
  content:
    author: true
    link: true
    title: false
    date: false
    updated: false
    license: true
    license_type: by-nc-sa
valine:
  enable: false
  serverURLs: null
  visitor: false
  pageSize: 10
  placeholder: Just go go
  highlight: true
  guest_info: nick,mail,link
  recordIP: true
  avatar: mp
  appId: null
  appKey: null
menu:
  - name: home
    url: /
    icon: null
  - name: archives
    url: /archives
    icon: null
  - name: about
    url: /about
    icon: null
  - name: links
    url: /friend
    icon: null
  - name: 写作后台
    url: /admin/
    icon: null
comment:
  title:
    en: Leave a comment
    zh-CN: 说些什么吧！
    zh-TW: 說些什麼吧！
    ja: コメントを残す
    pt-BR: Deixe um comentário
  default: waline
share: null
